# Generated by Django 3.2.9 on 2022-04-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_profile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
